#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Auto-setup script for IBC + IB Gateway on Windows VPS.
    Run once as Administrator. On every subsequent reboot,
    IB Gateway launches and logs in automatically.

.PREREQUISITE
    IB Gateway must already be installed to C:\Jts before running.
    Download: https://www.interactivebrokers.com/en/trading/ibgateway-stable.php

.USAGE
    Right-click PowerShell -> Run as Administrator
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
    .\setup_ibc.ps1
#>

# ── Config ────────────────────────────────────────────────────────────────────
$GatewayPath = "C:\Jts"
$IbcPath     = "C:\IBC"
$ibkrUser    = "debamamv07"
$ibkrPass    = "dev13579"
$tradingMode = "paper"
$port        = 4002

# ── Helpers ───────────────────────────────────────────────────────────────────
function Write-Step { param($msg) Write-Host "`n[*] $msg" -ForegroundColor Cyan }
function Write-OK   { param($msg) Write-Host "    [OK] $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "    [!!] $msg" -ForegroundColor Yellow }
function Write-Fail { param($msg) Write-Host "`n[ERROR] $msg`n" -ForegroundColor Red; exit 1 }

# ── Banner ────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "============================================================" -ForegroundColor Yellow
Write-Host "   IBC Auto-Setup for Windows VPS" -ForegroundColor Yellow
Write-Host "   Kaizen Intraday Semis - Production" -ForegroundColor Yellow
Write-Host "============================================================" -ForegroundColor Yellow
Write-Host ""
Write-Host "  IBKR User    : $ibkrUser" -ForegroundColor White
Write-Host "  Mode         : $tradingMode (port $port)" -ForegroundColor White
Write-Host "  IBC Path     : $IbcPath" -ForegroundColor White
Write-Host "  Gateway Path : $GatewayPath" -ForegroundColor White
Write-Host ""

# ── Step 0: Windows password for auto-logon ───────────────────────────────────
$winPassSS = Read-Host "  Enter Windows login password (for auto-logon)" -AsSecureString
$winPass   = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
                 [Runtime.InteropServices.Marshal]::SecureStringToBSTR($winPassSS))
if (-not $winPass) { Write-Fail "Windows password cannot be empty." }

Write-Host ""
Read-Host "  Ready. Press Enter to start, or Ctrl+C to cancel"

# ── Step 1: Detect IB Gateway ─────────────────────────────────────────────────
Write-Step "Detecting IB Gateway..."

if (-not (Test-Path $GatewayPath)) {
    Write-Fail "IB Gateway not found at $GatewayPath. Install it first."
}

$versionDirs = Get-ChildItem "$GatewayPath\ibgateway" -Directory -ErrorAction SilentlyContinue |
               Sort-Object Name -Descending

if ($versionDirs) {
    $twsVersion = $versionDirs[0].Name
    Write-OK "Detected version $twsVersion"
} else {
    Write-Warn "Could not auto-detect version from $GatewayPath\ibgateway\"
    $twsVersion = Read-Host "  Enter TWS version manually (e.g. 10.30)"
    if (-not $twsVersion) { Write-Fail "Version is required." }
}

# ── Step 2: Download IBC ──────────────────────────────────────────────────────
Write-Step "Downloading latest IBC from GitHub..."

try {
    $release = Invoke-RestMethod "https://api.github.com/repos/IbcAlpha/IBC/releases/latest" -UseBasicParsing
    $asset   = $release.assets | Where-Object { $_.name -like "IBCWindows*.zip" } | Select-Object -First 1
    if (-not $asset) { Write-Fail "IBCWindows zip not found in GitHub release." }
    $zipPath = "$env:TEMP\IBC_latest.zip"
    Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $zipPath -UseBasicParsing
    Write-OK "Downloaded IBC $($release.tag_name)"
} catch {
    Write-Fail "Download failed: $_"
}

# ── Step 3: Install IBC ───────────────────────────────────────────────────────
Write-Step "Installing IBC to $IbcPath..."

if (Test-Path $IbcPath) {
    Write-Warn "Backing up existing IBC to ${IbcPath}_backup"
    if (Test-Path "${IbcPath}_backup") { Remove-Item "${IbcPath}_backup" -Recurse -Force }
    Rename-Item $IbcPath "${IbcPath}_backup"
}

New-Item -ItemType Directory -Path $IbcPath -Force | Out-Null
Expand-Archive -Path $zipPath -DestinationPath $IbcPath -Force
New-Item -ItemType Directory -Path "$IbcPath\Logs" -Force | Out-Null
Write-OK "IBC installed"

# ── Step 4: Write config.ini ──────────────────────────────────────────────────
Write-Step "Writing config.ini..."

$lines = @(
    "# IBC Configuration - auto-generated by setup_ibc.ps1",
    "",
    "IbLoginId=$ibkrUser",
    "IbPassword=$ibkrPass",
    "TradingMode=$tradingMode",
    "IbDir=$GatewayPath",
    "",
    "AcceptIncomingConnectionAction=accept",
    "ReadonlyLogin=no",
    "ExistingSessionDetectedAction=primary",
    "AcceptNonBrokerageAccountWarning=yes",
    "ReloginAfterSecondFactorAuthenticationTimeout=yes",
    "SecondFactorAuthenticationExpiryAction=restart",
    "LogComponents=never"
)
$lines | Set-Content "$IbcPath\config.ini" -Encoding UTF8
Write-OK "config.ini written"

# ── Step 5: Write StartGateway.bat ────────────────────────────────────────────
Write-Step "Writing StartGateway.bat..."

$bat = @(
    "@echo off",
    "REM IBC Gateway Launcher - auto-generated by setup_ibc.ps1",
    "",
    "set TWS_MAJOR_VRSN=$twsVersion",
    "set IBC_INI=$IbcPath\config.ini",
    "set TWSUSERID=$ibkrUser",
    "set TWSPASSWORD=$ibkrPass",
    "set TRADING_MODE=$tradingMode",
    "set IBC_PATH=$IbcPath",
    "set TWS_PATH=$GatewayPath",
    "set LOG_PATH=$IbcPath\Logs",
    "set JAVA_PATH=",
    "set HIDE_CONSOLE=yes",
    "",
    "cd /D ""%IBC_PATH%""",
    "call ""%IBC_PATH%\Scripts\DisplayBannerAndLaunch.bat"""
)
$bat | Set-Content "$IbcPath\StartGateway.bat" -Encoding ASCII
Write-OK "StartGateway.bat written"

# ── Step 6: Task Scheduler ────────────────────────────────────────────────────
Write-Step "Registering Task Scheduler job 'IBC_Gateway'..."

$taskName = "IBC_Gateway"
Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue

$action    = New-ScheduledTaskAction -Execute "$IbcPath\StartGateway.bat"
$trigger   = New-ScheduledTaskTrigger -AtStartup
$trigger.Delay = "PT30S"
$settings  = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Hours 0) `
    -RestartCount 5 `
    -RestartInterval (New-TimeSpan -Minutes 2) `
    -StartWhenAvailable `
    -RunOnlyIfNetworkAvailable
$principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Highest

Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger `
    -Settings $settings -Principal $principal -Force | Out-Null

Write-OK "Task 'IBC_Gateway' registered (fires 30s after every boot)"

# ── Step 7: Windows Auto-Logon ────────────────────────────────────────────────
Write-Step "Enabling Windows auto-logon..."

$reg = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"
Set-ItemProperty $reg "AutoAdminLogon"    "1"               -Type String
Set-ItemProperty $reg "DefaultUserName"   "$env:USERNAME"   -Type String
Set-ItemProperty $reg "DefaultPassword"   "$winPass"        -Type String
Set-ItemProperty $reg "DefaultDomainName" "$env:USERDOMAIN" -Type String

Write-OK "Auto-logon enabled for $env:USERNAME"

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host "   Setup Complete!" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  IBC Path     : $IbcPath" -ForegroundColor White
Write-Host "  Config       : $IbcPath\config.ini" -ForegroundColor White
Write-Host "  Launcher     : $IbcPath\StartGateway.bat" -ForegroundColor White
Write-Host "  Port         : $port ($tradingMode)" -ForegroundColor White
Write-Host "  Task         : IBC_Gateway (30s after boot)" -ForegroundColor White
Write-Host "  Auto-logon   : Enabled for $env:USERNAME" -ForegroundColor White
Write-Host ""
Write-Host "  NEXT: Reboot the VPS." -ForegroundColor Yellow
Write-Host "  Boot flow: Windows auto-logon -> IBC -> IB Gateway -> IBKR login -> port $port ready" -ForegroundColor Gray
Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
